// <auto-generated>
//  由权威源生成，勿手改色值：
//   · 12 个语义色（18 套 = 9 皮肤 × 浅/深）：KeyBox/src/index.css → 安卓 Skins.kt（含 WCAG-AA 校准）
//   · id/label/hint：KeyBox/src/lib/theme.ts
//   · 圆角/字距/字体/阴影：KeyBox/src/index.css 各皮肤块
//  生成器：tools 脚本（见提交信息）；若要改配色，请改上游客源后重新生成。
// </auto-generated>

#nullable enable

namespace KeyBox.App.Theme;

/// <summary>一套皮肤的 12 个语义色（Web --kb-* / 安卓 SkinPalette 一一对应）。</summary>
public sealed record SkinColors(
    string Background, string Surface, string SurfaceVariant, string OnSurface, string OnSurfaceVariant,
    string Outline, string OutlineVariant, string Primary, string OnPrimary,
    string Error, string Success, string Warning);

/// <summary>皮肤的非颜色令牌（形状/字体），照 index.css 各皮肤块。</summary>
public sealed record SkinShape(
    double Radius, double CardRadius, double HeadingTracking, string? FontFamily, string ShadowRecipe);

/// <summary>皮肤元信息（与 Web theme.ts / 安卓 KeyBoxSkin 完全一致，顺序即展示顺序）。</summary>
public sealed record SkinInfo(string Id, string Label, string Hint);

/// <summary>KeyBox 主题数据源：9 皮肤 × 2 明暗 = 18 套。</summary>
public static class SkinPalettes
{
    /// <summary>展示顺序即 Web 端顺序。</summary>
    public static readonly SkinInfo[] Skins =
    {
        new("default", "精致克制", "白/深蓝底，品牌靛蓝点缀，细边框小圆角"),
        new("tech", "现代科技感", "深邃底色 + 发光层次，突出保险箱的科技感"),
        new("minimal", "极简商务", "无圆角无阴影，靠留白与字距分层"),
        new("paper", "纸质档案感", "米黄纸底 + 衬线字 + 红色套色，像纸质密钥簿"),
        new("cyber", "赛博朋克", "霓虹品红 + 电光青，暗底发光，最张扬"),
        new("kawaii", "可爱风", "粉白底 + 超大圆角 + 柔光，圆润讨喜"),
        new("hacker", "极客终端", "荧光绿字黑屏 + 等宽字体，终端味十足"),
        new("solar", "护眼自然", "低饱和莫兰迪，长时间看最不累眼"),
        new("sunset", "暖阳", "暖橙渐层，明快温暖有活力"),
    };

    private static readonly Dictionary<string, SkinColors> Light = new(StringComparer.OrdinalIgnoreCase)
    {
        ["default"] = new("F8FAFC","FFFFFF","EEF2F7","0F172A","64748B","CBD5E1","E2E8F0","4F46E5","FFFFFF","E11D48","059669","B45309"),
        ["tech"] = new("EEF2FB","FFFFFF","E8EDFA","0D1424","566178","B9C6EA","D8E0F5","5B53E8","FFFFFF","E11D48","059669","B45309"),
        ["minimal"] = new("FFFFFF","FFFFFF","FAFAFA","111111","8A8A8A","D4D4D4","ECECEC","111111","FFFFFF","B91C1C","15803D","A16207"),
        ["paper"] = new("F4EFE4","FBF8F1","F7F2E8","241F16","7A6F5B","B9AD95","DDD4C0","8C2B22","F8F3E9","9B2C1F","4F6B3A","8A6A1F"),
        ["cyber"] = new("F7F0FB","FFFFFF","F1E6F8","14061F","6B5A7A","C9A8E0","E3CFF0","D1007A","FFFFFF","E01B24","00A878","B26A00"),
        ["kawaii"] = new("FFF5F9","FFFFFF","FFEAF3","4A2B3A","9A7486","FFB8D6","FFD6E8","FF7AB6","FFFFFF","F0567A","4CC38A","E0A13C"),
        ["hacker"] = new("F2F5F0","FFFFFF","E8EFE6","0F1A10","4D6B50","A8C4A2","CFE0CB","12772F","FFFFFF","B3261E","12772F","8A6A1F"),
        ["solar"] = new("F4F0E6","FBF8F1","ECE7D9","3F4A44","7A8577","C2BCA8","DCD6C6","2F6F5E","FFFFFF","A8473C","4A7A52","8F6F2A"),
        ["sunset"] = new("FFF4EC","FFFFFF","FFEAD9","3D2517","8A6852","E8BD9A","F6DCC4","E2622A","FFFFFF","C0392B","3F8F5F","B07620"),
    };

    private static readonly Dictionary<string, SkinColors> Dark = new(StringComparer.OrdinalIgnoreCase)
    {
        ["default"] = new("0B1120","111A2E","182442","E6ECFF","97A6C9","334155","1E2B47","818CF8","0B1120","FB7185","34D399","FBBF24"),
        ["tech"] = new("070B16","0E1526","131D33","E6ECFF","97A6C9","2E3F63","1E2B47","818CF8","06101F","FB7185","34D399","FBBF24"),
        ["minimal"] = new("0A0A0A","111111","171717","F2F2F2","8F8F8F","3A3A3A","242424","F2F2F2","0A0A0A","F87171","4ADE80","FBBF24"),
        ["paper"] = new("1C1710","241E15","2B241A","ECD9B8","B09A76","5A4A33","3D3324","C9603F","1C1710","E0704F","8AA86A","D9A441"),
        ["cyber"] = new("07020F","120820","1A0D2E","F5E9FF","A08EC0","5B2F8A","3A1F5E","FF2FB0","07020F","FF4D6D","00E5A0","FFD166"),
        ["kawaii"] = new("2A1A24","3A2431","472C3C","FFE3F0","C9A2B6","7D4A64","5A3648","FF9AC9","2A1A24","FF90AC","7FD6AE","F0C070"),
        ["hacker"] = new("000000","0A0F0A","101A10","7BF58A","4FAE5D","2F5C34","1C3A1F","20FF5F","000000","FF5F5F","20FF5F","FFD75F"),
        ["solar"] = new("1E2318","252C1E","2D3625","DFE6D5","98A68C","4D5A3E","38422D","8FBF7F","1E2318","D98B7D","8FBF7F","D4B165"),
        ["sunset"] = new("1D1119","271A22","33222C","F7E4DC","C3A396","5C3F4A","422C35","FF8A4C","1D1119","FF7A6B","7FC79A","F0BB6A"),
    };

    /// <summary>皮肤形状令牌（浅/深共用；阴影配方按深浅不同，见 ShadowRecipeDark）。</summary>
    public static readonly Dictionary<string, SkinShape> Shapes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["default"] = new(10, 16, -0.01, "Segoe UI", "soft"),
        ["tech"] = new(12, 18, 0.01, "Segoe UI", "soft"),
        ["minimal"] = new(0, 0, 0.14, "Segoe UI", "none"),
        ["paper"] = new(2, 3, 0.06, "Georgia", "hard"),
        ["cyber"] = new(6, 10, 0.08, "Segoe UI", "glow"),
        ["kawaii"] = new(16, 24, 0.02, "Microsoft YaHei", "soft"),
        ["hacker"] = new(2, 3, 0.06, "Cascadia Code", "none"),
        ["solar"] = new(8, 12, 0.01, "Segoe UI", "soft"),
        ["sunset"] = new(12, 18, 0.01, "Segoe UI", "soft"),
    };

    public static SkinInfo GetInfo(string? id)
    {
        foreach (SkinInfo s in Skins) { if (string.Equals(s.Id, id, StringComparison.OrdinalIgnoreCase)) return s; }
        return Skins[0];
    }

    /// <summary>取某皮肤某明暗的 12 色；未知 id 回落 default。</summary>
    public static SkinColors Get(string? id, bool dark)
    {
        Dictionary<string, SkinColors> table = dark ? Dark : Light;
        if (id is not null && table.TryGetValue(id, out SkinColors? c)) return c;
        return table["default"];
    }

    public static SkinShape GetShape(string? id)
    {
        if (id is not null && Shapes.TryGetValue(id, out SkinShape? s)) return s;
        return Shapes["default"];
    }
}
